CREATE TABLE IF NOT EXISTS USER${YEAR} (
  ID BINARY(16) PRIMARY KEY,
  CREATE_TIME DATETIME,
  UPDATE_TIME DATETIME,
  CODE BIGINT UNSIGNED,
  DISPLAY_NAME VARCHAR(100),
  EMAIL VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS USER_DIMENSION${YEAR} (
  ID BINARY(16) PRIMARY KEY,
  CREATE_TIME DATETIME,
  UPDATE_TIME DATETIME,
  USER_ID BINARY(16),
  DIM_NAME VARCHAR(500),
  DIM_VALUE BINARY(16)
);

INSERT INTO USER${YEAR}(ID, CREATE_TIME, UPDATE_TIME, DISPLAY_NAME, EMAIL) VALUES (UUID_TO_BIN('{USER1_ID}'), #{TIME}, #{TIME}, {USER1_CODE}, 'flyingfish', 'hCXl0tRqp6g@qmail.com');
INSERT INTO USER${YEAR}(ID, CREATE_TIME, UPDATE_TIME, DISPLAY_NAME, EMAIL) VALUES (UUID_TO_BIN('{USER2_ID}'), #{TIME}, #{TIME}, {USER2_CODE}, 'divingcat', 'I3Cv-7-hBjk@vmail.com');

-- \{ABCDEFGHIJKLMNOPQRSTUVWXYZ\}
/* \{ZYXWVUTSRQPONMLKJIHGFEDCBA\} */
INSERT INTO USER_DIMENSION${YEAR}(ID, CREATE_TIME, UPDATE_TIME, USER_ID, DIM_NAME, DIM_VALUE) VALUES (UUID_TO_BIN(UUID()), #{TIME}, #{TIME}, UUID_TO_BIN('{USER1_ID}'), 'BBS_NRBLFHSV', UUID_TO_BIN('9a32463a300a6f492dfb16bf2f50ce58'));
INSERT INTO USER_DIMENSION${YEAR}(ID, CREATE_TIME, UPDATE_TIME, USER_ID, DIM_NAME, DIM_VALUE) VALUES (UUID_TO_BIN(UUID()), #{TIME}, #{TIME}, UUID_TO_BIN('{USER1_ID}'), 'GAME_TVMHSRM', UUID_TO_BIN('2e9f8f71b6f7b434bfa5c03e5f0d40d3'));
INSERT INTO USER_DIMENSION${YEAR}(ID, CREATE_TIME, UPDATE_TIME, USER_ID, DIM_NAME, DIM_VALUE) VALUES (UUID_TO_BIN(UUID()), #{TIME}, #{TIME}, UUID_TO_BIN('{USER1_ID}'), 'GAME_HGZIIZRO', UUID_TO_BIN('85447153b0ede2a8ec9ab3cc61defe48'));
INSERT INTO USER_DIMENSION${YEAR}(ID, CREATE_TIME, UPDATE_TIME, USER_ID, DIM_NAME, DIM_VALUE) VALUES (UUID_TO_BIN(UUID()), #{TIME}, #{TIME}, UUID_TO_BIN('{USER2_ID}'), 'BBS_NRBLFHSV', UUID_TO_BIN('bf2312129f116234a8d79cfb83bd9475'));
INSERT INTO USER_DIMENSION${YEAR}(ID, CREATE_TIME, UPDATE_TIME, USER_ID, DIM_NAME, DIM_VALUE) VALUES (UUID_TO_BIN(UUID()), #{TIME}, #{TIME}, UUID_TO_BIN('{USER2_ID}'), 'GAME_TVMHSRM', UUID_TO_BIN('b43db12a322cf37ee229aa1d5bf10080'));
INSERT INTO USER_DIMENSION${YEAR}(ID, CREATE_TIME, UPDATE_TIME, USER_ID, DIM_NAME, DIM_VALUE) VALUES (UUID_TO_BIN(UUID()), #{TIME}, #{TIME}, UUID_TO_BIN('{USER2_ID}'), 'GAME_HGZIIZRO', UUID_TO_BIN('805b7b9f97e1566c533060356a4edf84'));

SELECT T1.ID, T2.DIM_NAME, T2.DIM_VALUE
FROM USER${YEAR} T1
INNER JOIN USER_DIMENSION${YEAR} T2 ON T1.ID = T2.USER_ID
WHERE T1.CODE BETWEEN {START_CODE} AND {END_CODE}
  #{DIM_NAME_PARAM}
  AND T1.EMAIL LIKE '%mail.com'#{EMPTY_SQL};